# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#

version: 2.1
workflows:
  main:
    jobs:
      - build
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: true
    steps:
      - checkout
      - run: curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
      - run: sudo apt-get install --force-yes --allow-downgrades --allow-remove-essential --allow-change-held-packages -y nodejs
      - run: rm -fr /opt/circleci/.nvm
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: pwd && ls
      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run: echo $_JSON_APPLICATION_CREDENTIALS > ./creds.json
      # run tests!
      - run: GOOGLE_APPLICATION_CREDENTIALS=`realpath ./creds.json` npm test